export type ProductCategory =
  | "vegetables"
  | "fruits"
  | "spices"
  | "nuts"
  | "eggs"
  | "oils";

export type Product = {
  id: string;
  name: string;
  subtitle: string;
  category: ProductCategory;
  origin: string;
  type: "Organic" | "Regular";
  unit: string;
  marketAvg: number; // Al Aweer Rate
  myPrice: number; // MyVegMarket Price
  image: string;
  badgeColor: string;
  about?: string;
  packaging?: string;
  freshness?: string;
};

// ✅ better than /featured (prevents same image everywhere)
const U = (q: string, sig: number) =>
  `https://source.unsplash.com/1600x1000/?${encodeURIComponent(q)}&sig=${sig}`;

export const PRODUCTS: Product[] = [
  // ----------------------------
  // VEGETABLES
  // ----------------------------
  {
    id: "tomato-uae",
    name: "Tomato (Local)",
    subtitle: "Fresh Daily Supply • Per KG",
    category: "vegetables",
    origin: "UAE",
    type: "Regular",
    unit: "KG",
    marketAvg: 9.5,
    myPrice: 6.75,
    image: U("tomato vegetable fresh", 1),
    badgeColor: "bg-red-600",
    packaging: "Per KG",
    freshness: "Arrived This Morning",
    about:
      "Fresh local tomatoes with good firmness—ideal for restaurants and daily bulk cooking.",
  },
  {
    id: "cucumber-uae",
    name: "Cucumber (Local)",
    subtitle: "Crisp & Clean • 5kg Carton",
    category: "vegetables",
    origin: "UAE",
    type: "Regular",
    unit: "Carton",
    marketAvg: 22,
    myPrice: 18.5,
    image: U("cucumber vegetable fresh", 2),
    badgeColor: "bg-green-700",
    packaging: "5kg Carton",
    freshness: "Harvested 24h ago",
    about:
      "Crisp cucumbers for salads and juice bars. Clean grading and stable supply.",
  },
  {
    id: "bell-pepper-nl",
    name: "Bell Peppers Mix (Netherlands)",
    subtitle: "Red/Yellow/Green • 5kg Carton",
    category: "vegetables",
    origin: "Netherlands",
    type: "Regular",
    unit: "Carton",
    marketAvg: 85,
    myPrice: 72,
    image: U("bell pepper red yellow green", 3),
    badgeColor: "bg-emerald-700",
    packaging: "5kg Carton",
    freshness: "Chilled Import Stock",
    about:
      "Premium mixed bell peppers—great for salads, grills, and premium kitchen menus.",
  },
  {
    id: "onion-red-oman",
    name: "Red Onions (Oman)",
    subtitle: "Medium Size • 10kg Bag",
    category: "vegetables",
    origin: "Oman",
    type: "Regular",
    unit: "Bag",
    marketAvg: 32,
    myPrice: 26.5,
    image: U("red onions bag", 4),
    badgeColor: "bg-red-800",
    packaging: "10kg Bag",
    freshness: "Daily Supply",
    about:
      "Stable daily onion supply with consistent sizing—ideal for large kitchens.",
  },
  {
    id: "potato-egypt",
    name: "Potato (Egypt)",
    subtitle: "Washed & Graded • 10kg Bag",
    category: "vegetables",
    origin: "Egypt",
    type: "Regular",
    unit: "Bag",
    marketAvg: 28,
    myPrice: 23,
    image: U("potato bag washed", 5),
    badgeColor: "bg-amber-700",
    packaging: "10kg Bag",
    freshness: "New Batch This Week",
    about:
      "Washed and graded potatoes—perfect for fries, mash, and bulk prep.",
  },
  {
    id: "carrot-aus",
    name: "Carrot (Australia)",
    subtitle: "Crunchy & Sweet • 10kg Bag",
    category: "vegetables",
    origin: "Australia",
    type: "Regular",
    unit: "Bag",
    marketAvg: 38,
    myPrice: 32,
    image: U("carrot fresh", 6),
    badgeColor: "bg-orange-600",
    packaging: "10kg Bag",
    freshness: "Chilled Storage",
    about:
      "Premium carrots with consistent crunch—great for salads, juices and soups.",
  },
  {
    id: "broccoli-import",
    name: "Broccoli (Import)",
    subtitle: "Fresh Heads • 5kg Carton",
    category: "vegetables",
    origin: "China",
    type: "Regular",
    unit: "Carton",
    marketAvg: 55,
    myPrice: 49,
    image: U("broccoli fresh heads", 7),
    badgeColor: "bg-green-800",
    packaging: "5kg Carton",
    freshness: "Arrived This Week",
    about:
      "Fresh broccoli heads for steaming and stir-fry. Uniform size and stable supply.",
  },

  // ----------------------------
  // FRUITS
  // ----------------------------
  {
    id: "apple-turkey",
    name: "Apple (Turkey)",
    subtitle: "Crisp & Sweet • 18kg Carton",
    category: "fruits",
    origin: "Turkey",
    type: "Regular",
    unit: "Carton",
    marketAvg: 95,
    myPrice: 86,
    image: U("red apple carton", 8),
    badgeColor: "bg-red-600",
    packaging: "18kg Carton",
    freshness: "Import Batch Today",
    about:
      "Premium apples with strong crunch and shelf life—ideal for hotels and retail supply.",
  },
  {
    id: "banana-ecuador",
    name: "Banana (Ecuador)",
    subtitle: "Premium Grade • 13kg Carton",
    category: "fruits",
    origin: "Ecuador",
    type: "Regular",
    unit: "Carton",
    marketAvg: 62,
    myPrice: 56,
    image: U("banana bunch carton", 9),
    badgeColor: "bg-yellow-500",
    packaging: "13kg Carton",
    freshness: "Ripening Controlled",
    about:
      "Consistent size bananas—great for breakfast buffets, smoothie bars and grocery supply.",
  },
  {
    id: "grapes-india",
    name: "Green Grapes (India)",
    subtitle: "Seedless • 4.5kg Box",
    category: "fruits",
    origin: "India",
    type: "Regular",
    unit: "Box",
    marketAvg: 78,
    myPrice: 69,
    image: U("green grapes box", 10),
    badgeColor: "bg-emerald-600",
    packaging: "4.5kg Box",
    freshness: "Cold Chain Delivered",
    about:
      "Sweet seedless grapes for desserts and fruit platters—handled in cold chain.",
  },
  {
    id: "orange-egypt",
    name: "Valencia Oranges (Egypt)",
    subtitle: "Juice Grade • 15kg Carton",
    category: "fruits",
    origin: "Egypt",
    type: "Regular",
    unit: "Carton",
    marketAvg: 75,
    myPrice: 68,
    image: U("valencia oranges carton", 11),
    badgeColor: "bg-orange-600",
    packaging: "15kg Carton",
    freshness: "Import Batch Today",
    about:
      "Juicy oranges with consistent sweetness—perfect for juice stations and breakfast service.",
  },
  {
    id: "pineapple-ph",
    name: "Pineapple (Philippines)",
    subtitle: "Golden Sweet • 12pcs Carton",
    category: "fruits",
    origin: "Philippines",
    type: "Regular",
    unit: "Carton",
    marketAvg: 92,
    myPrice: 84,
    image: U("pineapple fruit carton", 12),
    badgeColor: "bg-amber-600",
    packaging: "12pcs Carton",
    freshness: "Chilled Import Stock",
    about:
      "Sweet pineapples with good yield for juice and dessert counters—ideal for catering.",
  },

  // ----------------------------
  // EGGS
  // ----------------------------
  {
    id: "eggs-brown-uae",
    name: "Brown Eggs (UAE)",
    subtitle: "Farm Fresh • 30 pcs Tray",
    category: "eggs",
    origin: "UAE",
    type: "Organic",
    unit: "Tray",
    marketAvg: 19,
    myPrice: 16.5,
    image: U("brown eggs tray", 13),
    badgeColor: "bg-neutral-700",
    packaging: "30 pcs Tray",
    freshness: "Collected Today",
    about:
      "Locally sourced brown eggs—perfect for bakeries, cafes and breakfast operations.",
  },
  {
    id: "white-eggs-uae",
    name: "White Eggs (UAE)",
    subtitle: "Daily Supply • 30 pcs Tray",
    category: "eggs",
    origin: "UAE",
    type: "Regular",
    unit: "Tray",
    marketAvg: 18,
    myPrice: 15.5,
    image: U("white eggs tray", 14),
    badgeColor: "bg-neutral-700",
    packaging: "30 pcs Tray",
    freshness: "Daily Delivery",
    about:
      "Clean white eggs with stable daily supply—best for restaurants and supermarkets.",
  },
  {
    id: "quail-eggs-uae",
    name: "Quail Eggs",
    subtitle: "Premium Pack • 24 pcs",
    category: "eggs",
    origin: "UAE",
    type: "Regular",
    unit: "Pack",
    marketAvg: 28,
    myPrice: 24,
    image: U("quail eggs pack", 15),
    badgeColor: "bg-zinc-800",
    packaging: "24 pcs Pack",
    freshness: "Chilled Stock",
    about:
      "Popular for gourmet plating and premium catering—packed clean and delivered chilled.",
  },

  // ----------------------------
  // SPICES
  // ----------------------------
  {
    id: "cardamom-green",
    name: "Cardamom (Green)",
    subtitle: "Aromatic Pods • 1kg Pack",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 0,
    myPrice: 0,
    image: U("green cardamom pods spice", 16),
    badgeColor: "bg-emerald-700",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Premium green cardamom—ideal for tea, desserts and masala blends.",
  },
  {
    id: "black-pepper",
    name: "Black Pepper",
    subtitle: "Whole Peppercorn • 1kg Pack",
    category: "spices",
    origin: "Vietnam",
    type: "Regular",
    unit: "KG",
    marketAvg: 0,
    myPrice: 0,
    image: U("black peppercorns spice", 17),
    badgeColor: "bg-neutral-800",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Whole peppercorns with strong pungency—perfect for kitchens and grinders.",
  },
  {
    id: "turmeric",
    name: "Turmeric Powder",
    subtitle: "Fine Ground • 1kg Pack",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 0,
    myPrice: 0,
    image: U("turmeric powder spice", 18),
    badgeColor: "bg-yellow-600",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Bright color and aroma—best for curries, marinades and bulk cooking.",
  },
  {
    id: "clove",
    name: "Clove",
    subtitle: "Whole Buds • 1kg Pack",
    category: "spices",
    origin: "Indonesia",
    type: "Regular",
    unit: "KG",
    marketAvg: 0,
    myPrice: 0,
    image: U("cloves spice whole", 19),
    badgeColor: "bg-amber-800",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Whole clove buds—great for biryani, tea and spice mixes.",
  },
  {
    id: "cinnamon-sticks",
    name: "Cinnamon Sticks",
    subtitle: "Whole Sticks • 1kg Pack",
    category: "spices",
    origin: "Sri Lanka",
    type: "Regular",
    unit: "KG",
    marketAvg: 0,
    myPrice: 0,
    image: U("cinnamon sticks spice", 20),
    badgeColor: "bg-orange-700",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Premium cinnamon sticks—perfect for desserts, beverages and aroma-rich cooking.",
  },
  {
    id: "bay-leaf",
    name: "Bay Leaf",
    subtitle: "Whole Leaves • 500g Pack",
    category: "spices",
    origin: "Turkey",
    type: "Regular",
    unit: "Pack",
    marketAvg: 0,
    myPrice: 0,
    image: U("bay leaves spice", 21),
    badgeColor: "bg-green-700",
    packaging: "500g Pack",
    freshness: "Sealed Pack",
    about: "Clean bay leaves for soups, curries and rice dishes—packed for bulk kitchens.",
  },
  {
    id: "star-anise",
    name: "Star Anise",
    subtitle: "Whole Spice • 1kg Pack",
    category: "spices",
    origin: "China",
    type: "Regular",
    unit: "KG",
    marketAvg: 0,
    myPrice: 0,
    image: U("star anise spice", 22),
    badgeColor: "bg-yellow-900",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Strong aroma—ideal for biryani masala and premium spice blends.",
  },

  // ----------------------------
  // NUTS
  // ----------------------------
  {
    id: "cashew",
    name: "Cashew Nuts",
    subtitle: "Whole Premium • 10kg Carton",
    category: "nuts",
    origin: "Vietnam",
    type: "Regular",
    unit: "Carton",
    marketAvg: 0,
    myPrice: 0,
    image: U("cashew nuts", 23),
    badgeColor: "bg-amber-600",
    packaging: "10kg Carton",
    freshness: "Sealed Carton",
    about: "Whole cashews for sweets, snacks and bulk kitchen use.",
  },
  {
    id: "almond",
    name: "Almond",
    subtitle: "Premium Grade • 10kg Carton",
    category: "nuts",
    origin: "USA",
    type: "Regular",
    unit: "Carton",
    marketAvg: 0,
    myPrice: 0,
    image: U("almonds nuts", 24),
    badgeColor: "bg-rose-700",
    packaging: "10kg Carton",
    freshness: "Sealed Carton",
    about: "Crunchy almonds for bakeries, cafes and retail packing.",
  },
  {
    id: "walnut",
    name: "Walnut",
    subtitle: "Shelled • 10kg Carton",
    category: "nuts",
    origin: "Chile",
    type: "Regular",
    unit: "Carton",
    marketAvg: 0,
    myPrice: 0,
    image: U("walnuts shelled", 25),
    badgeColor: "bg-stone-700",
    packaging: "10kg Carton",
    freshness: "Sealed Carton",
    about: "Premium walnuts—perfect for desserts, salads and healthy mixes.",
  },
  {
    id: "dates",
    name: "Dates",
    subtitle: "Premium Grade • 5kg Box",
    category: "nuts",
    origin: "UAE",
    type: "Regular",
    unit: "Box",
    marketAvg: 0,
    myPrice: 0,
    image: U("dates fruit box", 26),
    badgeColor: "bg-amber-800",
    packaging: "5kg Box",
    freshness: "Packed Fresh",
    about: "Soft premium dates for retail, gifting and hotel breakfast service.",
  },
  {
    id: "raisins",
    name: "Dry Grapes (Raisins)",
    subtitle: "Golden Raisins • 5kg Pack",
    category: "nuts",
    origin: "Turkey",
    type: "Regular",
    unit: "Pack",
    marketAvg: 0,
    myPrice: 0,
    image: U("golden raisins", 27),
    badgeColor: "bg-yellow-700",
    packaging: "5kg Pack",
    freshness: "Sealed Pack",
    about: "Golden raisins for bakeries, desserts and bulk mixes.",
  },
  {
    id: "pista",
    name: "Pistachio",
    subtitle: "Premium • 10kg Carton",
    category: "nuts",
    origin: "Iran",
    type: "Regular",
    unit: "Carton",
    marketAvg: 0,
    myPrice: 0,
    image: U("pistachios", 28),
    badgeColor: "bg-lime-700",
    packaging: "10kg Carton",
    freshness: "Sealed Carton",
    about: "Premium pistachios for sweets, ice cream, bakeries and retail packs.",
  },

  // ----------------------------
  // OILS
  // ----------------------------
  {
    id: "olive-oil",
    name: "Olive Oil",
    subtitle: "Extra Virgin • 5L Tin",
    category: "oils",
    origin: "Spain",
    type: "Regular",
    unit: "Tin",
    marketAvg: 0,
    myPrice: 0,
    image: U("olive oil bottle", 29),
    badgeColor: "bg-green-700",
    packaging: "5L Tin",
    freshness: "Sealed Pack",
    about: "Premium olive oil for salads, cooking and horeca supply.",
  },
  {
    id: "sunflower-oil",
    name: "Sunflower Oil",
    subtitle: "Cooking Oil • 5L Bottle",
    category: "oils",
    origin: "Ukraine",
    type: "Regular",
    unit: "Bottle",
    marketAvg: 0,
    myPrice: 0,
    image: U("sunflower oil bottle", 30),
    badgeColor: "bg-yellow-600",
    packaging: "5L Bottle",
    freshness: "Sealed Pack",
    about: "Everyday cooking oil for restaurants and bulk kitchens.",
  },
  {
    id: "groundnut-oil",
    name: "Groundnut Oil",
    subtitle: "High Heat Cooking • 5L Bottle",
    category: "oils",
    origin: "India",
    type: "Regular",
    unit: "Bottle",
    marketAvg: 0,
    myPrice: 0,
    image: U("peanut oil bottle", 31),
    badgeColor: "bg-orange-700",
    packaging: "5L Bottle",
    freshness: "Sealed Pack",
    about: "Good for frying and high-heat cooking with a clean taste.",
  },
  {
    id: "sesame-oil",
    name: "Sesame Oil",
    subtitle: "Aromatic • 1L Bottle",
    category: "oils",
    origin: "India",
    type: "Regular",
    unit: "Bottle",
    marketAvg: 0,
    myPrice: 0,
    image: U("sesame oil bottle", 32),
    badgeColor: "bg-amber-700",
    packaging: "1L Bottle",
    freshness: "Sealed Pack",
    about: "Aromatic sesame oil—best for flavor-rich cooking and marinades.",
  },
];
